import { Link } from 'react-router-dom';

const C = { bg:'#04060e', green:'#0ff078', text:'#b8d0e8', sub:'#3a5068', card:'#080d1a', border:'#0f1e30', red:'#f0365a' };

function Section({ title, children }) {
  return (
    <div style={{ marginBottom:40 }}>
      <h2 style={{ color:'#e8f4ff', fontSize:18, fontWeight:700, marginBottom:16, paddingBottom:8, borderBottom:`1px solid ${C.border}` }}>{title}</h2>
      <div style={{ color:'#8ab0cc', fontSize:14, lineHeight:1.9 }}>{children}</div>
    </div>
  );
}

export default function Terms() {
  return (
    <div style={{ minHeight:'100vh', background:C.bg }}>
      <nav style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'20px 5%', borderBottom:`1px solid ${C.border}` }}>
        <Link to="/" style={{ color:C.green, fontWeight:800, fontSize:20, textDecoration:'none' }}>NEXUS</Link>
        <Link to="/login" style={{ color:C.text, textDecoration:'none', fontSize:14 }}>Sign In</Link>
      </nav>

      <div style={{ maxWidth:800, margin:'0 auto', padding:'60px 5%' }}>
        <h1 style={{ color:'#e8f4ff', fontSize:36, fontWeight:800, marginBottom:8 }}>Terms of Service</h1>
        <p style={{ color:C.sub, fontSize:14, marginBottom:48 }}>Last updated: April 16, 2026</p>

        {/* Critical Risk Warning */}
        <div style={{ background:`${C.red}12`, border:`2px solid ${C.red}44`, borderRadius:10, padding:'24px', marginBottom:48 }}>
          <h2 style={{ color:C.red, fontSize:16, fontWeight:800, marginBottom:12 }}>⚠ CRITICAL RISK WARNING — READ BEFORE USING</h2>
          <p style={{ color:'#d4a0a0', fontSize:14, lineHeight:1.8, marginBottom:10 }}>
            <strong>Cryptocurrency trading carries an extremely high risk of financial loss.</strong> The automated trading features of NEXUS execute real financial transactions on your behalf. You may lose your entire investment. Do not invest funds you cannot afford to lose.
          </p>
          <p style={{ color:'#d4a0a0', fontSize:14, lineHeight:1.8, marginBottom:10 }}>
            <strong>NEXUS is not a licensed financial adviser, broker, investment manager, or registered investment adviser.</strong> Nothing in this Service constitutes financial, investment, legal, or tax advice. All trading decisions are made by automated algorithms with no human oversight.
          </p>
          <p style={{ color:'#d4a0a0', fontSize:14, lineHeight:1.8 }}>
            <strong>NEXUS and its operators accept no responsibility or liability for any financial losses, trading losses, or consequential damages arising from use of this Service.</strong> By using NEXUS, you explicitly assume all financial risk.
          </p>
        </div>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using NEXUS ("Service," "Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you and NEXUS.</p>
          <p style={{ marginTop:12 }}>You must be at least 18 years of age and legally permitted to engage in cryptocurrency trading in your jurisdiction to use this Service.</p>
        </Section>

        <Section title="2. Service Description">
          <p>NEXUS provides automated cryptocurrency trading software that analyzes market data and executes buy and sell orders on supported cryptocurrency exchanges using API keys you provide. The Service operates as a software tool only.</p>
          <p style={{ marginTop:12 }}>The Service is provided in two modes: (a) Paper Trading, which simulates trades without real money, and (b) Live Trading, which executes real transactions on your connected exchange accounts. You are solely responsible for selecting and monitoring the trading mode.</p>
        </Section>

        <Section title="3. No Financial Advice">
          <p>NEXUS does not provide financial advice, investment advice, trading advice, or any other type of advice. The Service is an automated software tool that executes predefined algorithmic strategies.</p>
          <p style={{ marginTop:12 }}>All trading signals, decisions, and executions are generated by algorithms. These algorithms are not personalized to your financial situation, risk tolerance, investment objectives, or tax status. You should consult a licensed financial adviser before engaging in any cryptocurrency trading.</p>
        </Section>

        <Section title="4. Risk Acknowledgment">
          <p>By using this Service, you expressly acknowledge and accept that:</p>
          <ul style={{ paddingLeft:20, marginTop:8 }}>
            {[
              'Cryptocurrency markets are highly volatile and unpredictable',
              'Automated trading algorithms can and do make losing trades',
              'You may lose some or all of your invested capital',
              'Past performance of any algorithm does not guarantee future results',
              'The value of cryptocurrencies can decrease to zero',
              'Technical failures, API outages, or network issues may cause missed or erroneous trades',
              'Exchange fees, slippage, and market impact will reduce returns',
              'Regulatory changes may affect the legality or availability of cryptocurrency trading in your jurisdiction',
              'NEXUS does not guarantee any specific return or profit',
            ].map(i => <li key={i} style={{ marginBottom:6 }}>{i}</li>)}
          </ul>
        </Section>

        <Section title="5. Account Responsibilities">
          <p>You are responsible for:</p>
          <ul style={{ paddingLeft:20, marginTop:8 }}>
            {[
              'Maintaining the security and confidentiality of your account credentials',
              'All activity that occurs under your account',
              'Ensuring your exchange API keys have appropriate permissions (trade and read only — never withdrawal)',
              'Complying with all applicable laws and regulations in your jurisdiction regarding cryptocurrency trading',
              'Paying all applicable taxes on trading gains',
              'Monitoring your account and bot performance',
            ].map(i => <li key={i} style={{ marginBottom:6 }}>{i}</li>)}
          </ul>
        </Section>

        <Section title="6. Exchange API Keys and Fund Custody">
          <p>When you connect exchange API keys, NEXUS executes trades on your behalf through those keys. <strong style={{ color:'#e8f4ff' }}>NEXUS never takes custody of your funds.</strong> Your cryptocurrency remains in your exchange account at all times.</p>
          <p style={{ marginTop:12 }}>You should only grant API keys with "Trade" and "Read" permissions. Never grant withdrawal permissions to NEXUS or any third-party service. NEXUS is not responsible for unauthorized access to your exchange accounts or API keys.</p>
        </Section>

        <Section title="7. Subscription and Billing">
          <p>The Service offers a 14-day free trial period. After the trial period, continued use requires a paid subscription at $29.99 per month.</p>
          <p style={{ marginTop:12 }}>Subscriptions are billed monthly in advance. You may cancel at any time through the billing portal; cancellation takes effect at the end of the current billing period. No refunds are provided for partial months.</p>
          <p style={{ marginTop:12 }}>We reserve the right to change pricing with 30 days' notice. Continued use of the Service after a price change constitutes acceptance of the new pricing.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p><strong style={{ color:'#e8f4ff' }}>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEXUS AND ITS OPERATORS, AFFILIATES, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:</strong></p>
          <ul style={{ paddingLeft:20, marginTop:8 }}>
            {[
              'Any financial losses or trading losses incurred through use of the Service',
              'Loss of profits, revenue, or business opportunities',
              'Loss of data or interruption of service',
              'Losses arising from exchange API failures, market disruptions, or technical issues',
              'Any decisions made in reliance on information provided by the Service',
            ].map(i => <li key={i} style={{ marginBottom:6 }}>{i}</li>)}
          </ul>
          <p style={{ marginTop:12 }}>In jurisdictions that do not allow the exclusion of certain warranties or limitation of liability, our liability is limited to the maximum extent permitted by law. In no event shall our total liability exceed the amount you paid for the Service in the three months preceding the claim.</p>
        </Section>

        <Section title="9. Indemnification">
          <p>You agree to indemnify, defend, and hold harmless NEXUS and its operators, affiliates, officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, and expenses (including legal fees) arising from your use of the Service, violation of these Terms, or violation of any applicable law or third-party rights.</p>
        </Section>

        <Section title="10. Service Availability">
          <p>We strive for high availability but do not guarantee uninterrupted service. The Service may be unavailable due to maintenance, technical issues, third-party API failures, or circumstances beyond our control. We are not liable for losses resulting from service unavailability.</p>
        </Section>

        <Section title="11. Prohibited Uses">
          <p>You may not use the Service to:</p>
          <ul style={{ paddingLeft:20, marginTop:8 }}>
            {[
              'Violate any applicable law or regulation',
              'Engage in market manipulation or wash trading',
              'Circumvent exchange terms of service',
              'Attempt to reverse-engineer or copy the Service',
              'Share your account with others',
              'Use the Service in jurisdictions where it is prohibited',
            ].map(i => <li key={i} style={{ marginBottom:6 }}>{i}</li>)}
          </ul>
        </Section>

        <Section title="12. Modifications and Termination">
          <p>We reserve the right to modify these Terms at any time with 30 days' notice. We may suspend or terminate your account for violation of these Terms, non-payment, or at our discretion with 30 days' notice.</p>
        </Section>

        <Section title="13. Governing Law">
          <p>These Terms are governed by applicable law. Any disputes shall be resolved through binding arbitration rather than in court, except for claims eligible for small claims court. You waive any right to a jury trial or to participate in a class action lawsuit.</p>
        </Section>

        <Section title="14. Entire Agreement">
          <p>These Terms, together with our Privacy Policy, constitute the entire agreement between you and NEXUS regarding the Service and supersede all prior agreements. If any provision is found unenforceable, the remaining provisions remain in full force.</p>
        </Section>
      </div>

      <footer style={{ borderTop:`1px solid ${C.border}`, padding:'24px 5%', textAlign:'center', color:C.sub, fontSize:12 }}>
        <Link to="/" style={{ color:C.green, textDecoration:'none', marginRight:24 }}>NEXUS</Link>
        <Link to="/privacy" style={{ color:C.sub, textDecoration:'none', marginRight:24 }}>Privacy Policy</Link>
        © 2026 NEXUS. All rights reserved.
      </footer>
    </div>
  );
}
